name: controls_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - decorator==5.2.1
      - etils==1.13.0
      - freetype-py==2.5.1
      - glfw==2.10.0
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - lxml==6.0.2
      - mujoco==3.3.6
      - networkx==2.2
      - numpy==1.23.5
      - pillow==11.3.0
      - pycollada==0.6
      - pyglet==2.1.9
      - pyopengl==3.1.0
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - scipy==1.15.3
      - six==1.17.0
      - trimesh==4.8.3
      - urdfpy==0.0.22
      - zipp==3.23.0
